# Generated by Django 3.1.7 on 2021-08-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('planning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='open_trip_map_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
