# Generated by Django 3.1.7 on 2021-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0002_place_dataset_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque efficitur posuere. Curabitur tincidunt placerat diam ac efficitur. Cras rutrum egestas nisl vitae pulvinar. Donec id mollis diam, id hendrerit neque.', max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
