# Generated by Django 3.1.7 on 2021-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0002_placereview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='properties',
        ),
        migrations.AddField(
            model_name='place',
            name='properties',
            field=models.ManyToManyField(to='planning_app.Property'),
        ),
    ]
