# Generated by Django 3.1.7 on 2021-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0002_place_open_trip_map_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
