# Generated by Django 3.1.7 on 2021-08-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('planning_app', '0003_auto_20210827_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'Extended'), (2, 'Focused')], default=1),
        ),
    ]
