# Generated by Django 3.1.7 on 2021-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0003_auto_20210816_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='place',
            name='properties',
            field=models.ManyToManyField(related_name='places', to='planning_app.Property'),
        ),
    ]
