# Generated by Django 3.1.7 on 2021-08-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0004_trip_trip_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.CreateModel(
            name='GeoNameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_name_id', models.CharField(max_length=15)),
                ('country_name', models.CharField(max_length=36)),
                ('wiki_link', models.URLField()),
                ('wiki_title', models.CharField(max_length=255)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_name_info', to='planning_app.place')),
            ],
        ),
    ]
