# Generated by Django 3.1.7 on 2021-08-16 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0006_placereview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='overall_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
