# Generated by Django 3.1.7 on 2021-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0008_remove_place_guest_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.IntegerField(choices=[(1, 'Place'), (2, 'Hotel')], default=1),
        ),
    ]
