# Generated by Django 3.1.7 on 2021-08-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0009_auto_20210816_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planning_app.trip'),
        ),
    ]
