# Generated by Django 3.1.7 on 2021-08-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning_app', '0010_auto_20210817_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='planning_app.place'),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
