# Generated by Django 3.1.7 on 2021-08-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0011_auto_20210817_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='main_activity',
            field=models.CharField(default='touring', max_length=50),
            preserve_default=False,
        ),
    ]
