# Generated by Django 3.1.7 on 2021-08-17 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0012_day_main_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='places',
        ),
        migrations.AlterField(
            model_name='day',
            name='day_index',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning_app.day')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning_app.place')),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='main_activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_in', to='planning_app.activity'),
        ),
    ]
