# Generated by Django 3.1.7 on 2021-08-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0013_auto_20210817_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='main_activity',
        ),
    ]
