# Generated by Django 3.1.7 on 2021-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0014_remove_day_main_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='review_text',
            field=models.CharField(max_length=700),
        ),
    ]
