# Generated by Django 3.1.7 on 2021-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0015_auto_20210818_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
