# Generated by Django 3.1.7 on 2021-08-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0016_place_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
