# Generated by Django 3.1.7 on 2021-08-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_deviceinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'verbose_name': 'Device info', 'verbose_name_plural': 'Devices info'},
        ),
    ]
