# Generated by Django 3.1.7 on 2021-04-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefedditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeddItem',
            new_name='ProfileFeedItem',
        ),
    ]
