# Generated by Django 3.1.7 on 2021-08-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20210814_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
