# Generated by Django 3.1.7 on 2021-08-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20210815_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthDay',
            new_name='birthday',
        ),
    ]
