# Generated by Django 3.1.7 on 2021-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20210425_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ranking',
            field=models.FloatField(default=0.0),
        ),
    ]
