# Generated by Django 3.1.7 on 2021-04-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_place_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.location'),
            preserve_default=False,
        ),
    ]
