# Generated by Django 3.1.7 on 2021-05-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20210425_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartialRating',
        ),
        migrations.AddField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles_api.location'),
        ),
    ]
