# Generated by Django 3.1.7 on 2021-05-20 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_auto_20210502_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=50),
        ),
    ]
