# Generated by Django 3.1.7 on 2021-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_place_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='ranking',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.AddField(
            model_name='place',
            name='kinds',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.CharField(max_length=2000),
        ),
    ]
