# Generated by Django 3.1.7 on 2021-08-13 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('distance', models.FloatField(default=0.0)),
                ('guestrating', models.FloatField(default=0.0,
                                                  validators=[django.core.validators.MinValueValidator(0.0),
                                                              django.core.validators.MaxValueValidator(5.0)])),
                ('kinds', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('imageUri', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('cityName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('distance', models.FloatField(default=0.0)),
                ('guestrating', models.FloatField(default=0.0,
                                                  validators=[django.core.validators.MinValueValidator(0.0),
                                                              django.core.validators.MaxValueValidator(5.0)])),
                ('kinds', models.CharField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('imageUri', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkinDate', models.DateTimeField()),
                ('checkoutDate', models.DateTimeField()),
                ('details', models.CharField(max_length=1000)),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=2000)),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_api.place')),
            ],
        ),
    ]
