# Generated by Django 3.1.7 on 2021-08-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('cityName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('distance', models.FloatField(default=0.0)),
                ('guestrating', models.FloatField(default=0.0)),
                ('kinds', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('imageUri', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotels_api.place')),
            ],
            bases=('hotels_api.place',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkinDate', models.DateTimeField()),
                ('checkoutDate', models.DateTimeField()),
                ('details', models.CharField(max_length=1000)),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_api.place')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=2000)),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_api.place')),
            ],
        ),
    ]
