# Generated by Django 3.1.7 on 2021-08-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='placeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_api.hotel'),
        ),
    ]
