# Generated by Django 3.1.7 on 2021-07-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0002_auto_20210602_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
