# Generated by Django 3.1.7 on 2021-08-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0003_auto_20210814_1954'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloghastag',
            unique_together={('blog_id', 'tag_id')},
        ),
    ]
