# Generated by Django 3.1.7 on 2021-08-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0004_auto_20210814_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloghastag',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bloghastag',
            constraint=models.UniqueConstraint(fields=('blog_id', 'tag_id'), name='uniqueness'),
        ),
    ]
