# Generated by Django 3.1.7 on 2021-07-14 10:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0004_auto_20210712_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=10000),
        ),
    ]
