# Generated by Django 3.1.7 on 2021-08-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_api', '0005_auto_20210814_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='hotels_api.Tag'),
        ),
        migrations.DeleteModel(
            name='BlogHasTag',
        ),
    ]
