# Generated by Django 3.1.7 on 2021-08-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger_app', '0009_userlikeblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikeblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
