# Generated by Django 3.1.7 on 2021-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger_app', '0010_auto_20210819_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikeblog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
