# Generated by Django 3.1.7 on 2021-08-19 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger_app', '0011_auto_20210819_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikeblog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
